
// filepath: /Users/jameslin/Documents/GitHub/shixuanLin1009.github.io/_config.yml
# Site settings
title: "Shixuan Lin - Personal Website"
email: NM6144046@gs.ncku.edu.tw
description: >- # this means to ignore newlines until "baseurl:"
  A personal website showcasing my research, projects, and blog posts.
  PhD student sharing insights on machine learning and data science.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shixuanlin1009.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username: shixuanLin1009

# Author information
author:
  name: "Shixuan Lin"
  email: "NM6144046@gs.ncku.edu.tw"
  bio: "PhD Student | Researcher | Developer"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
